### ISSUE TITLE
Panic while syncing

### ISSUE THREAD

**Issue by heki-ru** [ava-labs/subnet-evm#1200]
Was syncing from scratch DFK subnet and it's crashed

```
{
    "state-sync-enabled": true,
    "state-sync-min-blocks": 86400,
    "validatorOnly": true,
    "metrics-expensive-enabled": false
}
```

```
Ubuntu 24.04
Linux 6.8.0-31-generic #31-Ubuntu SMP PREEMPT_DYNAMIC Sat Apr 20 00:40:06 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
subnet-evm v0.6.5
avalanchego v1.11.6
```

[q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi.log](https://github.com/user-attachments/files/15523410/q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi.log)

```
[06-01|05:46:30.315] INFO <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> sync/statesync/trie_sync_stats.go:137 state sync: syncing storage tries        triesRemaining=169  ETA=1h12m
[06-01|05:47:30.399] INFO <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> sync/statesync/trie_sync_stats.go:137 state sync: syncing storage tries        triesRemaining=157  ETA=1h10m
[06-01|05:48:30.470] INFO <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> sync/statesync/trie_sync_stats.go:137 state sync: syncing storage tries        triesRemaining=157  ETA=1h7m
[06-01|05:49:30.525] INFO <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> sync/statesync/trie_sync_stats.go:137 state sync: syncing storage tries        triesRemaining=45   ETA=59m
panic: send on closed channel

goroutine 321 [running]:
github.com/ava-labs/subnet-evm/sync/statesync.(*trieToSync).createSegments(0xc000769340, 0x4)
	/home/runner/work/subnet-evm/subnet-evm/subnet-evm/sync/statesync/trie_segments.go:312 +0x2c7
github.com/ava-labs/subnet-evm/sync/statesync.(*trieToSync).createSegmentsIfNeeded(0xc000528320?, 0x7c659164e460?)
	/home/runner/work/subnet-evm/subnet-evm/subnet-evm/sync/statesync/trie_segments.go:248 +0x33
github.com/ava-labs/subnet-evm/sync/statesync.(*trieSegment).OnLeafs(0xc0001b2000, {0xc001cc8000?, 0x400, 0x555}, {0xc001cf0000, 0x400, 0x555})
	/home/runner/work/subnet-evm/subnet-evm/subnet-evm/sync/statesync/trie_segments.go:381 +0x285
github.com/ava-labs/subnet-evm/sync/client.(*CallbackLeafSyncer).syncTask(0xc001016330, {0x1a6b9e8, 0xc001031770}, {0x1a724f0, 0xc0001b2000})
	/home/runner/work/subnet-evm/subnet-evm/subnet-evm/sync/client/leaf_syncer.go:127 +0x365
github.com/ava-labs/subnet-evm/sync/client.(*CallbackLeafSyncer).workerLoop(0xc001016330, {0x1a6b9e8, 0xc001031770})
	/home/runner/work/subnet-evm/subnet-evm/subnet-evm/sync/client/leaf_syncer.go:70 +0xd0
github.com/ava-labs/subnet-evm/sync/client.(*CallbackLeafSyncer).Start.func1()
	/home/runner/work/subnet-evm/subnet-evm/subnet-evm/sync/client/leaf_syncer.go:154 +0x1f
golang.org/x/sync/errgroup.(*Group).Go.func1()
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:78 +0x56
created by golang.org/x/sync/errgroup.(*Group).Go in goroutine 258
	/home/runner/go/pkg/mod/golang.org/x/sync@v0.6.0/errgroup/errgroup.go:75 +0x96
[06-01|05:49:38.103] INFO <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> subprocess/runtime.go:111 stdout collector shutdown
[06-01|05:49:38.103] INFO <q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi Chain> subprocess/runtime.go:124 stderr collector shutdown
```

**Comment by ceyonur** [comment]
Is this reproducible after restarts? What happened after you retried to bootstrap with same configurations?

**Comment by heki-ru** [comment]
[q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi.log](https://github.com/user-attachments/files/15534524/q2aTwKuyzgs8pynF7UXBZCU7DejbZbZ6EUyHr3JQzYgwNPUPi.log)

After node restart it continued syncing and successful finished it. I don't know if it's possible to reproduce, because it was one time occasional panic.
