### ISSUE TITLE
Investigate CI test failure TestDatabaseRollback

### ISSUE THREAD

**Issue by darioush** [ava-labs/subnet-evm#1300]
-test.shuffle 1724274607158782700 (windows)
https://github.com/ava-labs/subnet-evm/actions/runs/10497423009/job/29080239137?pr=1298#step:7:110

```
--- FAIL: TestDatabaseRollback (0.00s)
panic: failed to update state changes, err: layer cycle [recovered]
	panic: failed to update state changes, err: layer cycle

goroutine 12 [running]:
testing.tRunner.func1.2({0x1410ddf40, 0xc0037e7680})
	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1545 +0x3f7
testing.tRunner.func1()
	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1548 +0x716
panic({0x1410ddf40?, 0xc0037e7680?})
	C:/hostedtoolcache/windows/go/1.21.13/x64/src/runtime/panic.go:920 +0x270
github.com/ava-labs/subnet-evm/trie/triedb/pathdb.newTester(0x40?, 0x0)
	D:/a/subnet-evm/subnet-evm/trie/triedb/pathdb/database_test.go:136 +0x7d2
github.com/ava-labs/subnet-evm/trie/triedb/pathdb.TestDatabaseRollback(0x0?)
	D:/a/subnet-evm/subnet-evm/trie/triedb/pathdb/database_test.go:365 +0x45
testing.tRunner(0xc00182cb60, 0x14127de08)
	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1595 +0x262
created by testing.(*T).Run in goroutine 1
	C:/hostedtoolcache/windows/go/1.21.13/x64/src/testing/testing.go:1648 +0x846
```

**Comment by darioush** [comment]
Also observed:
```
--- FAIL: TestJournal (0.00s)
panic: failed to update state changes, err: layer cycle [recovered]
	panic: failed to update state changes, err: layer cycle
```
https://github.com/ava-labs/subnet-evm/actions/runs/10633532948/attempts/1

**Comment by michaelkaplan13** [comment]
Closing as stale
