### ISSUE TITLE
Legacy pre-eip-155 transactions not supported

### ISSUE THREAD

**Issue by Uponn** [ava-labs/subnet-evm#280]
**Describe the bug**
Hey, I'm following [this ](https://docs.avax.network/subnets/deploy-a-gnosis-safe-on-your-evm#custom-network-workflow) guide from the site for deploying a Gnosis Safe on my subnet. I'm getting the following error:
```
C:\Users\Steliyan\Desktop\safe-contracts>yarn hardhat deploy --network subnet           
yarn run v1.22.18
$ C:\Users\Steliyan\Desktop\safe-contracts\node_modules\.bin\hardhat deploy --network subnet
Nothing to compile
sending eth to create2 contract deployer address (0x3fab184622dc19b6109349b94811493bf2a45362) (tx: 0x571c252c750e3cf8c86138035b7c8007fd7dde7c928178fb3524740338a7678d)...
deploying create2 deployer contract (at 0x4e59b44847b379578588920ca78fbf26c0b4956c) using deterministic deployment (https://github.com/Arachnid/deterministic-deployment-proxy)An unexpected error occurred:

Error: ERROR processing C:\Users\Steliyan\Desktop\safe-contracts\src\deploy\deploy_accessors.ts:
Error: legacy pre-eip-155 transactions not supported (error={"name":"ProviderError","code":-32000,"_isProviderError":true}, method="sendTransaction", transaction="0xf8a58085174876e800830186a08080b853604580600e600039806000f350fe7fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe03601600081602082378035828234f58015156039578182fd5b8082525050506014600cf31ba02222222222222222222222222222222222222222222222222222222222222222a02222222222222222222222222222222222222222222222222222222222222222", code=UNSUPPORTED_OPERATION, version=providers/5.4.5)
    at Logger.makeError (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\node_modules\@ethersproject\logger\src.ts\index.ts:225:28)
    at Logger.throwError (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\node_modules\@ethersproject\logger\src.ts\index.ts:237:20)
    at checkError (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:74:16)
    at Web3Provider.<anonymous> (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\node_modules\@ethersproject\providers\src.ts\json-rpc-provider.ts:555:20)
    at step (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:48:23)
    at Object.throw (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:29:53)
    at rejected (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\node_modules\@ethersproject\providers\lib\json-rpc-provider.js:21:65)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.executeDeployScripts (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:1108:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at DeploymentsManager.runDeploy (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\src\DeploymentsManager.ts:938:5)
    at Environment._runTaskDefinition (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\src\index.ts:546:32)
    at Environment._runTaskDefinition (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
    at Environment.run (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:129:14)
    at SimpleTaskDefinition.action (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat-deploy\src\index.ts:630:5)
    at Environment._runTaskDefinition (C:\Users\Steliyan\Desktop\safe-contracts\node_modules\hardhat\src\internal\core\runtime-environment.ts:217:14)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**To Reproduce**
run:
```
hardhat deploy --network subnet
```

**Additional context**
my hardhat.config.ts
```
subnet: {
      url: `${NODE_URL}`,
      chainId: 43214913,
      gasPrice: "auto",
      accounts: [`${PK}`],
    },
```

Also on my own explorer I can see the initial transaction.

**Comment by aaronbuchwald** [comment]
There is a config option to protect against pre-EIP 155 transactions since they do not provide replay protection: https://docs.avax.network/nodes/maintain/chain-config-flags#allow-unprotected-txs-boolean. The default is that you cannot send non-replay protected transactions, but you can toggle this option if you need to allow for unprotected transactions.

**Comment by aaronbuchwald** [comment]
Merged this PR https://github.com/ava-labs/subnet-evm/pull/377 to unblock special case pre-EIP-155 transactions like this one: https://github.com/ava-labs/subnet-evm/pull/377. This has been included in the latest subnet-evm release https://github.com/ava-labs/subnet-evm/releases/tag/v0.4.4.
