### ISSUE TITLE
Feeding subnet-evm with faulty upgrade.json results in panic

### ISSUE THREAD

**Issue by holisticode** [ava-labs/subnet-evm#460]
**Describe the bug**
Install faulty upgrade.json to node:
```
{
  "precompileUpgrades": {
      "feeManagerConfig": {
        "blockTimestamp": 1668950000,
        "adminAddresses": ["0x8db97C7cEcE249c2b98bDC0226Cc4C2A57BF52FC"]
      }
    }
}
```
(might not be the exact `upgrade.json` which failed as it got overwritten now)

**To Reproduce**
Install faulty upgrade.json to node and start

**Expected behavior**
Should gracefully handle

**Screenshots**
```
INFO [01-26|14:57:25.580] <kXG6HvtqcSoEHhkbVDdhQukZNgMPeKqzqiaJ1znXjkH1Tpitg Chain> github.com/ava-labs/subnet-evm/eth/backend.go:134: Allocated memory caches trie clean=512.00MiB trie dirty=256.00MiB snapshot clean=256.00MiB
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x561a62]

goroutine 12 [running]:
math/big.(*Int).Cmp(0xac660b?, 0x0?)
        /opt/hostedtoolcache/go/1.18.9/x64/src/math/big/int.go:328 +0x22
github.com/ava-labs/subnet-evm/commontype.(*FeeConfig).Verify(0xc000638840)
        /home/runner/work/subnet-evm/subnet-evm/subnet-evm/commontype/fee_config.go:65 +0x2f
github.com/ava-labs/subnet-evm/precompile.(*FeeConfigManagerConfig).Verify(0xc0005d6280)
        /home/runner/work/subnet-evm/subnet-evm/subnet-evm/precompile/fee_config_manager.go:141 +0x3d
github.com/ava-labs/subnet-evm/params.(*ChainConfig).verifyPrecompileUpgrades(0xc0005ff320)
        /home/runner/work/subnet-evm/subnet-evm/subnet-evm/params/precompile_config.go:156 +0x230
github.com/ava-labs/subnet-evm/params.(*ChainConfig).Verify(0xc0005ff320)
```

**Operating System**
linux

**Comment by aaronbuchwald** [comment]
Addressed by https://github.com/ava-labs/subnet-evm/pull/461

**Comment by ceyonur** [comment]
Hm this might be different than #461 since this one occured on fee config `Verify`. It seems like the given initial fee config has an empty field of `gasLimit`. We should be checking that in verify, thanks!

Created https://github.com/ava-labs/subnet-evm/pull/473
